<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Craftsvilla" duration-ms="68238" started-at="2019-12-07T16:30:06Z" finished-at="2019-12-07T16:31:14Z">
    <groups>
    </groups>
    <test name="Regression" duration-ms="68238" started-at="2019-12-07T16:30:06Z" finished-at="2019-12-07T16:31:14Z">
      <class name="com.craftsvilla.testscripts.LinenSareesScripts">
        <test-method status="PASS" signature="openApp(java.lang.String)[pri:0, instance:com.craftsvilla.testscripts.LinenSareesScripts@5474c6c]" name="openApp" is-config="true" duration-ms="44303" started-at="2019-12-07T16:30:06Z" finished-at="2019-12-07T16:30:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="FAIL" signature="TC_01_linenSareeScript()[pri:0, instance:com.craftsvilla.testscripts.LinenSareesScripts@5474c6c]" name="TC_01_linenSareeScript" duration-ms="19745" started-at="2019-12-07T16:30:50Z" finished-at="2019-12-07T16:31:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.craftsvilla.testscripts.LinenSareesScripts.TC_01_linenSareeScript(LinenSareesScripts.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_linenSareeScript -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:com.craftsvilla.testscripts.LinenSareesScripts@5474c6c]" name="closeApp" is-config="true" duration-ms="1686" started-at="2019-12-07T16:31:12Z" finished-at="2019-12-07T16:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.craftsvilla.testscripts.LinenSareesScripts -->
    </test> <!-- Regression -->
  </suite> <!-- Craftsvilla -->
</testng-results>
